export const REVIEW_TRACKS = [
  {
    id: 'elementary',
    title: 'Elementary LET',
    description: 'General Education and Professional Education review path for Elementary LET examinees.',
    categoryIds: ['gened', 'profed'],
    requiresSpecialization: false,
    isPublished: true,
  },
  {
    id: 'secondary',
    title: 'Secondary LET',
    description: 'General Education, Professional Education, and Field of Specialization review path for Secondary LET examinees.',
    categoryIds: ['gened', 'profed', 'major'],
    requiresSpecialization: true,
    specializationOptions: ['Mathematics'],
    isPublished: true,
  },
  {
    id: 'specialization',
    title: 'Field of Specialization Focus',
    description: 'Focused review path for students who want to repair or strengthen one specialization area first.',
    categoryIds: ['major'],
    requiresSpecialization: true,
    specializationOptions: ['Mathematics'],
    isPublished: true,
  },
];

export const CATEGORIES = [
  { id: 'gened', name: 'General Education', description: 'Core subjects including English, Math, Science, and Social Sciences.', reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed', name: 'Professional Education', description: 'Teaching profession, child development, and pedagogy.', reviewTracks: ['elementary', 'secondary'] },
  { id: 'major', name: 'Field of Specialization', description: 'Secondary LET specialization content such as Mathematics, English, Filipino, Science, and other majors.', reviewTracks: ['secondary', 'specialization'] }
];

export const TOPICS = [
  { id: 'gened_english', categoryId: 'gened', name: 'English Communication', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'gened_math', categoryId: 'gened', name: 'Mathematics', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'gened_science', categoryId: 'gened', name: 'Science', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'gened_socsci', categoryId: 'gened', name: 'Social Science', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed_assessment', categoryId: 'profed', name: 'Assessment of Learning', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed_principles', categoryId: 'profed', name: 'Principles of Teaching', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed_childdev', categoryId: 'profed', name: 'Child and Adolescent Development', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed_curriculum', categoryId: 'profed', name: 'Curriculum Development', isPublished: true, reviewTracks: ['elementary', 'secondary'] },
  { id: 'major_math', categoryId: 'major', name: 'Mathematics: Number Sense and Problem Solving', isPublished: true, reviewTracks: ['secondary', 'specialization'], specialization: 'Mathematics' }
];

export const SKILLS = [
  { id: 'profed_assessment_summative', topicId: 'profed_assessment', categoryId: 'profed', name: 'Summative Assessment', reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed_assessment_formative', topicId: 'profed_assessment', categoryId: 'profed', name: 'Formative Assessment', reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed_assessment_validity_reliability', topicId: 'profed_assessment', categoryId: 'profed', name: 'Validity vs Reliability', reviewTracks: ['elementary', 'secondary'] },
  { id: 'gened_math_algebra', topicId: 'gened_math', categoryId: 'gened', name: 'Algebra', reviewTracks: ['elementary', 'secondary'] },
  { id: 'gened_english_grammar', topicId: 'gened_english', categoryId: 'gened', name: 'Grammar', reviewTracks: ['elementary', 'secondary'] },
  { id: 'gened_english_inference', topicId: 'gened_english', categoryId: 'gened', name: 'Inference and Evidence', reviewTracks: ['elementary', 'secondary'] },
  { id: 'gened_socsci_civics', topicId: 'gened_socsci', categoryId: 'gened', name: 'Civics and Philippine Government', reviewTracks: ['elementary', 'secondary'] },
  { id: 'profed_childdev_stage_theory', topicId: 'profed_childdev', categoryId: 'profed', name: 'Development Stage Theory', reviewTracks: ['elementary', 'secondary'] },
  { id: 'major_math_ratio', topicId: 'major_math', categoryId: 'major', name: 'Ratios and Proportion', reviewTracks: ['secondary', 'specialization'], specialization: 'Mathematics' },
  { id: 'major_math_number_sense', topicId: 'major_math', categoryId: 'major', name: 'Number Sense', reviewTracks: ['secondary', 'specialization'], specialization: 'Mathematics' }
];

export const TEXTBOOKS = [
  {
    id: 'book_gened_communication_foundations',
    title: 'General Education Reviewer: Communication Foundations',
    author: 'Let Mastery Editorial Team',
    categoryId: 'gened',
    topicId: 'gened_english',
    description: 'Evidence-based reading, grammar traps, vocabulary, and LET-style passage strategies.',
    pages: 86,
    readTime: '2h 10m',
    level: 'Core',
    chapter: 'Chapter 2',
    isPublished: true,
    offlineReady: true,
    sections: [
      { title: 'Reading for Purpose', minutes: 8, body: 'Identify the question type before reading the full passage.' },
      { title: 'Evidence Beats Familiarity', minutes: 10, body: 'Reject answers that repeat words but change the supported idea.' }
    ]
  },
  {
    id: 'book_gened_math_foundations',
    title: 'General Education Reviewer: Math Foundations',
    author: 'Let Mastery Editorial Team',
    categoryId: 'gened',
    topicId: 'gened_math',
    description: 'Number sense, basic operations, prime numbers, ratios, and common LET math traps.',
    pages: 72,
    readTime: '1h 50m',
    level: 'Core',
    chapter: 'Chapter 3',
    isPublished: true,
    offlineReady: true,
    sections: [
      { title: 'Number Properties', minutes: 8, body: 'Prime numbers have exactly two factors: 1 and themselves.' },
      { title: 'Check the Operation', minutes: 8, body: 'Name what the problem asks before choosing an operation.' }
    ]
  },
  {
    id: 'book_profed_assessment_alignment',
    title: 'Professional Education Reviewer: Assessment and Alignment',
    author: 'Prof. Reyes',
    categoryId: 'profed',
    topicId: 'profed_assessment',
    description: 'Formative assessment, constructive alignment, rubrics, validity, reliability, and feedback.',
    pages: 112,
    readTime: '3h',
    level: 'Teaching Practice',
    chapter: 'Chapter 5',
    isPublished: true,
    offlineReady: true,
    sections: [
      { title: 'Outcomes First', minutes: 9, body: 'Match assessments to the verb and performance named in the learning outcome.' },
      { title: 'Formative Evidence', minutes: 7, body: 'Use checks during learning before making final achievement judgments.' }
    ]
  },
  {
    id: 'book_profed_child_development',
    title: 'Child and Adolescent Development Quick Textbook',
    author: 'Dr. Jane Teacher',
    categoryId: 'profed',
    topicId: 'profed_childdev',
    description: 'Piaget, Erikson, Vygotsky, motivation, individual differences, and learner-centered decisions.',
    pages: 74,
    readTime: '1h 45m',
    level: 'Teaching Practice',
    chapter: 'Chapter 3',
    isPublished: true,
    offlineReady: true,
    sections: [
      { title: 'Piaget and Cognitive Readiness', minutes: 8, body: 'Match classroom tasks to learners cognitive development.' },
      { title: 'Erikson and Identity', minutes: 8, body: 'Use psychosocial stages to interpret learner needs.' }
    ]
  },
  {
    id: 'book_major_math_number_sense',
    title: 'Mathematics Major Reviewer: Number Sense',
    author: 'Ms. Dela Cruz',
    categoryId: 'major',
    topicId: 'major_math',
    description: 'Ratios, proportion, estimation, operations, and translating word problems into equations.',
    pages: 98,
    readTime: '2h 30m',
    level: 'Specialization',
    chapter: 'Chapter 1',
    isPublished: true,
    offlineReady: true,
    sections: [
      { title: 'Label the Quantities', minutes: 8, body: 'Name units before writing a proportion.' },
      { title: 'Estimate Before Solving', minutes: 6, body: 'Predict whether an answer should be larger or smaller before calculating.' }
    ]
  }
];

export const INITIAL_QUESTIONS = [
  // --- DIAGNOSTIC (General Education) ---
  {
    stem: "Which philosophy of education strongly emphasizes the back-to-basics curriculum?",
    options: [{id: 'A', text: 'Essentialism'}, {id: 'B', text: 'Progressivism'}, {id: 'C', text: 'Existentialism'}, {id: 'D', text: 'Perennialism'}],
    correctOptionId: 'A',
    explanation: 'Essentialism focuses on core skills and academic knowledge that all students should possess.',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_socsci',
    skillIds: [],
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "The smallest prime number is ________.",
    options: [{id: 'A', text: '0'}, {id: 'B', text: '1'}, {id: 'C', text: '2'}, {id: 'D', text: '3'}],
    correctOptionId: 'C',
    explanation: '2 is the only even prime number and the smallest prime number.',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_math',
    skillIds: ['gened_math_algebra'],
    competencyId: 'gened_math_algebra',
    familyId: 'fam_gened_math_prime_number',
    variantId: 'fam_gened_math_prime_number_v1',
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "Which option names the smallest prime number?",
    options: [{id: 'A', text: '1'}, {id: 'B', text: '2'}, {id: 'C', text: '3'}, {id: 'D', text: '5'}],
    correctOptionId: 'B',
    explanation: '2 is the smallest prime number because it has exactly two factors: 1 and 2.',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_math',
    skillIds: ['gened_math_algebra'],
    competencyId: 'gened_math_algebra',
    familyId: 'fam_gened_math_prime_number',
    variantId: 'fam_gened_math_prime_number_v2',
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "Who was the Filipino hero known as the 'Sublime Paralytic'?",
    options: [{id: 'A', text: 'Jose Rizal'}, {id: 'B', text: 'Andres Bonifacio'}, {id: 'C', text: 'Apolinario Mabini'}, {id: 'D', text: 'Emilio Aguinaldo'}],
    correctOptionId: 'C',
    explanation: 'Apolinario Mabini was a key revolutionary leader despite his physical disability.',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_socsci',
    skillIds: [],
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "In the sentence 'She is a shining star', what figure of speech is used?",
    options: [{id: 'A', text: 'Simile'}, {id: 'B', text: 'Metaphor'}, {id: 'C', text: 'Hyperbole'}, {id: 'D', text: 'Oxymoron'}],
    correctOptionId: 'B',
    explanation: 'A metaphor makes a direct comparison without using \"like\" or \"as\".',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_english',
    skillIds: ['gened_english_grammar'],
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  // --- DIAGNOSTIC (Professional Education) ---
  {
    stem: "According to Piaget, in which stage do children begin to think logically about concrete events?",
    options: [{id: 'A', text: 'Sensorimotor'}, {id: 'B', text: 'Pre-operational'}, {id: 'C', text: 'Concrete Operational'}, {id: 'D', text: 'Formal Operational'}],
    correctOptionId: 'C',
    explanation: 'The Concrete Operational stage (7-11 years) is characterized by logical thinking about tangible items.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_childdev',
    skillIds: [],
    difficulty: 'medium',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "What is the primary psychosocial crisis of adolescence according to Erikson?",
    options: [{id: 'A', text: 'Trust vs. Mistrust'}, {id: 'B', text: 'Identity vs. Role Confusion'}, {id: 'C', text: 'Intimacy vs. Isolation'}, {id: 'D', text: 'Industry vs. Inferiority'}],
    correctOptionId: 'B',
    explanation: 'Adolescents struggle with developing a sense of self and personal identity.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_childdev',
    skillIds: [],
    difficulty: 'medium',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "Which of the following is an example of an extrinsic motivation?",
    options: [{id: 'A', text: 'Learning for the joy of it'}, {id: 'B', text: 'Studying to get a high grade'}, {id: 'C', text: 'Reading a book out of curiosity'}, {id: 'D', text: 'Solving puzzles for fun'}],
    correctOptionId: 'B',
    explanation: 'Extrinsic motivation comes from outside rewards rather than internal satisfaction.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_principles',
    skillIds: [],
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "What type of assessment is given before instruction to determine students' entry knowledge?",
    options: [{id: 'A', text: 'Formative'}, {id: 'B', text: 'Summative'}, {id: 'C', text: 'Diagnostic'}, {id: 'D', text: 'Placement'}],
    correctOptionId: 'C',
    explanation: 'Diagnostic assessments identify strengths and weaknesses before teaching starts.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_assessment',
    skillIds: [],
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "Which of the following is a formative assessment technique?",
    options: [{id: 'A', text: 'Final exam'}, {id: 'B', text: 'Midterm paper'}, {id: 'C', text: 'Exit ticket'}, {id: 'D', text: 'Standardized test'}],
    correctOptionId: 'C',
    explanation: 'Exit tickets are used to check understanding during the lesson to inform instruction.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_assessment',
    skillIds: ['profed_assessment_formative'],
    competencyId: 'profed_assessment_formative',
    familyId: 'fam_profed_assessment_formative_examples',
    variantId: 'fam_profed_assessment_formative_examples_v1',
    difficulty: 'easy',
    type: 'diagnostic',
    isPublished: true,
    approved: true
  },
  {
    stem: "A teacher asks students to write one thing they understood and one question they still have before leaving class. What kind of assessment is this?",
    options: [{id: 'A', text: 'Formative assessment'}, {id: 'B', text: 'Summative assessment'}, {id: 'C', text: 'Placement assessment'}, {id: 'D', text: 'Norm-referenced assessment'}],
    correctOptionId: 'A',
    explanation: 'This is formative because the teacher uses evidence during learning to adjust instruction.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_assessment',
    skillIds: ['profed_assessment_formative'],
    competencyId: 'profed_assessment_formative',
    familyId: 'fam_profed_assessment_formative_examples',
    variantId: 'fam_profed_assessment_formative_examples_v2',
    difficulty: 'medium',
    type: 'practice',
    isPublished: true,
    approved: true
  },
  // --- PRACTICE ---
  {
    stem: "A word that has the same or nearly the same meaning as another word is called a ________.",
    options: [{id: 'A', text: 'Antonym'}, {id: 'B', text: 'Synonym'}, {id: 'C', text: 'Homonym'}, {id: 'D', text: 'Acronym'}],
    correctOptionId: 'B',
    explanation: 'Synonyms are words with similar meanings.',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_english',
    skillIds: ['gened_english_grammar'],
    difficulty: 'easy',
    type: 'practice',
    isPublished: true,
    approved: true
  },
  {
    stem: "In Bloom's Taxonomy, which level involves the ability to break down information into its component parts?",
    options: [{id: 'A', text: 'Knowledge'}, {id: 'B', text: 'Application'}, {id: 'C', text: 'Analysis'}, {id: 'D', text: 'Synthesis'}],
    correctOptionId: 'C',
    explanation: 'Analysis involves breaking down complex info into manageable parts.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_principles',
    skillIds: [],
    difficulty: 'medium',
    type: 'practice',
    isPublished: true,
    approved: true
  },
  // --- MOCK EXAM ---
  {
    stem: "Which of the following is the ultimate goal of the K-12 Curriculum in the Philippines?",
    options: [{id: 'A', text: 'Global competitiveness'}, {id: 'B', text: 'Holistic development'}, {id: 'C', text: 'College readiness'}, {id: 'D', text: 'Employment'}],
    correctOptionId: 'B',
    explanation: 'The K-12 program aims to produce holistically developed Filpinos with 21st-century skills.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_curriculum',
    skillIds: [],
    difficulty: 'hard',
    type: 'mock_exam',
    isPublished: true,
    approved: true
  },
  {
    stem: "In a frequency distribution, what is the score that occurs most frequently?",
    options: [{id: 'A', text: 'Mean'}, {id: 'B', text: 'Median'}, {id: 'C', text: 'Mode'}, {id: 'D', text: 'Range'}],
    correctOptionId: 'C',
    explanation: 'The mode is the value that appears most often in a data set.',
    categoryId: 'profed',
    categoryName: 'Professional Education',
    topicId: 'profed_assessment',
    skillIds: ['profed_assessment_summative'],
    difficulty: 'easy',
    type: 'mock_exam',
    isPublished: true,
    approved: true
  },
  {
    stem: "Which of the following is a direct tax?",
    options: [{id: 'A', text: 'Value Added Tax'}, {id: 'B', text: 'Excise Tax'}, {id: 'C', text: 'Income Tax'}, {id: 'D', text: 'Customs Duty'}],
    correctOptionId: 'C',
    explanation: 'Income tax is paid directly by an individual to the government.',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_socsci',
    skillIds: [],
    difficulty: 'medium',
    type: 'mock_exam',
    isPublished: true,
    approved: true
  },
  {
    stem: "The fundamental law of the land in the Philippines is the ________.",
    options: [{id: 'A', text: 'Civil Code'}, {id: 'B', text: 'Constitution'}, {id: 'C', text: 'Penal Code'}, {id: 'D', text: 'Family Code'}],
    correctOptionId: 'B',
    explanation: 'The Constitution is the supreme law of the Philippines.',
    categoryId: 'gened',
    categoryName: 'General Education',
    topicId: 'gened_socsci',
    skillIds: [],
    difficulty: 'easy',
    type: 'mock_exam',
    isPublished: true,
    approved: true
  },
  {
    stem: "A class has 18 boys and 12 girls. What is the ratio of boys to girls in simplest form?",
    options: [{id: 'A', text: '3:2'}, {id: 'B', text: '2:3'}, {id: 'C', text: '18:30'}, {id: 'D', text: '6:5'}],
    correctOptionId: 'A',
    explanation: 'The ratio 18:12 can be divided by 6, giving 3:2. Keep the order boys to girls.',
    categoryId: 'major',
    categoryName: 'Field of Specialization',
    topicId: 'major_math',
    skillIds: ['major_math_ratio'],
    competencyId: 'major_math_ratio',
    familyId: 'fam_major_math_ratio_simplify',
    variantId: 'fam_major_math_ratio_simplify_v1',
    difficulty: 'easy',
    type: 'practice',
    specialization: 'Mathematics',
    isPublished: true,
    approved: true
  },
  {
    stem: "A recipe uses 6 cups of flour for every 4 cups of sugar. What is the ratio of flour to sugar in simplest form?",
    options: [{id: 'A', text: '2:3'}, {id: 'B', text: '3:2'}, {id: 'C', text: '6:10'}, {id: 'D', text: '1:2'}],
    correctOptionId: 'B',
    explanation: 'The ratio 6:4 can be divided by 2, giving 3:2. The order is flour to sugar.',
    categoryId: 'major',
    categoryName: 'Field of Specialization',
    topicId: 'major_math',
    skillIds: ['major_math_ratio'],
    competencyId: 'major_math_ratio',
    familyId: 'fam_major_math_ratio_simplify',
    variantId: 'fam_major_math_ratio_simplify_v2',
    difficulty: 'easy',
    type: 'practice',
    specialization: 'Mathematics',
    isPublished: true,
    approved: true
  },
  {
    stem: "If 5 notebooks cost 150 pesos, how much will 8 notebooks cost at the same rate?",
    options: [{id: 'A', text: '200 pesos'}, {id: 'B', text: '240 pesos'}, {id: 'C', text: '250 pesos'}, {id: 'D', text: '300 pesos'}],
    correctOptionId: 'B',
    explanation: 'One notebook costs 150 / 5 = 30 pesos. Eight notebooks cost 8 x 30 = 240 pesos.',
    categoryId: 'major',
    categoryName: 'Field of Specialization',
    topicId: 'major_math',
    skillIds: ['major_math_ratio'],
    competencyId: 'major_math_ratio',
    difficulty: 'medium',
    type: 'mock_exam',
    specialization: 'Mathematics',
    isPublished: true,
    approved: true
  },
  {
    stem: "Which number is both a factor of 24 and a multiple of 3?",
    options: [{id: 'A', text: '5'}, {id: 'B', text: '6'}, {id: 'C', text: '8'}, {id: 'D', text: '10'}],
    correctOptionId: 'B',
    explanation: '6 is a factor of 24 because 24 / 6 = 4, and it is also a multiple of 3.',
    categoryId: 'major',
    categoryName: 'Field of Specialization',
    topicId: 'major_math',
    skillIds: ['major_math_number_sense'],
    competencyId: 'major_math_number_sense',
    difficulty: 'easy',
    type: 'diagnostic',
    specialization: 'Mathematics',
    isPublished: true,
    approved: true
  }
];
